import{a as L,i as m,S as v}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="https://pixabay.com/api/",S="46106680-1f6bf9cc8c5ebc2359fb269e0";async function g(s,t=1){const o={q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t},n=new URLSearchParams(o);return(await L.get(`${w}?key=${S}&${n}`)).data}document.querySelector(".gallery");function f(s){m.error({title:"Error",message:s})}function a(s){const t=document.querySelector(".loader");t.style.display=s?"block":"none"}function b(s,t){const o=s.hits.map(e=>`<li class="image">
        <a class = "gallery-link" href = "${e.largeImageURL}">  
        <img src = "${e.webformatURL}" alt = "${e.tags}" class = "image" />
        </a>
        <div class = "card-body">   
          <p class="text">Likes <span class = "value">${e.likes}</span></p>
          <p class="text">Views <span class = "value">${e.views}</span></p>
          <p class="text">Comments <span class = "value">${e.comments}</span></p>
          <p class="text">Downloads <span class = "value">${e.downloads}</span></p>
          </div>
        </li>`).join("");t.insertAdjacentHTML("beforeend",o),new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}document.head.insertAdjacentHTML("beforeend",`<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@0;1&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap" rel="stylesheet">`);let l=document.querySelector(".gallery");const y=document.querySelector(".btn"),p=document.querySelector(".container");let i=document.querySelector(".load-btn"),d=1,c="",h=0;async function q(s){if(s.preventDefault(),l.innerHTML="",i.classList.add("visually-hidden"),c=p.elements.query.value.trim(),d=1,!c){a(!1),f("Sorry, there are no images matching your search query. Please try again!");return}y.disabled=!0,a(!0);try{const t=await g(c,d);if(a(!1),t.hits.length===0){f("Sorry, there are no images matching your search query. Please try again!");return}else h=t.totalHits,b(t,l);l.children.length<h?(a(!0),i.classList.remove("visually-hidden")):i.classList.add("visually-hidden"),p.reset()}catch(t){f(t.message),a(!1)}finally{a(!1),y.disabled=!1}}async function P(){d+=1,a(!0);try{const s=await g(c,d);a(!1),b(s,l);const{height:t}=document.querySelector(".image img").getBoundingClientRect();if(window.scrollBy({top:t*2,behavior:"smooth"}),l.children.length>=h)return a(!1),i.classList.add("visually-hidden"),m.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(s){console.log(s),a(!1)}finally{a(!1)}}p.addEventListener("submit",q);i.addEventListener("click",P);
//# sourceMappingURL=index.js.map
