import{a as L,i as g,S as w}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const S="https://pixabay.com/api/",q="46106680-1f6bf9cc8c5ebc2359fb269e0";async function b(t,r=1){const n={q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r},a=new URLSearchParams(n);return(await L.get(`${S}?key=${q}&${a}`)).data}document.querySelector(".gallery");const P=document.querySelector(".div-loader"),x=document.querySelector(".div-loader-2");function p(t){g.error({title:"Error",message:t})}function h(t){P.style.visibility=t?"visible":"hidden"}function i(t){x.style.visibility=t?"visible":"hidden"}function v(t,r){const n=t.hits.map(e=>`<li class="image">
        <a class = "gallery-link" href = "${e.largeImageURL}">  
        <img src = "${e.webformatURL}" alt = "${e.tags}" class = "image" />
        </a>
        <div class = "card-body">   
          <p class="text">Likes <span class = "value">${e.likes}</span></p>
          <p class="text">Views <span class = "value">${e.views}</span></p>
          <p class="text">Comments <span class = "value">${e.comments}</span></p>
          <p class="text">Downloads <span class = "value">${e.downloads}</span></p>
          </div>
        </li>`).join("");r.insertAdjacentHTML("beforeend",n),new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}document.head.insertAdjacentHTML("beforeend",`<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@0;1&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap" rel="stylesheet">`);let l=document.querySelector(".gallery");const m=document.querySelector(".btn"),f=document.querySelector(".container");let o=document.querySelector(".load-btn"),d=1,c="",y=0;async function $(t){if(t.preventDefault(),l.innerHTML="",c=f.elements.query.value.trim(),d=1,!c){p("Sorry, there are no images matching your search query. Please try again!"),o.style.display="none";return}h(!0),o.style.display="none",m.disabled=!0;try{const r=await b(c,d);if(o.style.display="flex",r.hits.length===0){p("Sorry, there are no images matching your search query. Please try again!"),o.style.display="none";return}y=r.totalHits,v(r,l),l.children.length<y&&i(!1),f.reset()}catch(r){p(r.message)}finally{h(!1),m.disabled=!1}}async function k(){d+=1,i(!0);try{const t=await b(c,d);v(t,l);const{height:r}=document.querySelector(".image img").getBoundingClientRect();if(window.scrollBy({top:r*2,behavior:"smooth"}),l.children.length>=y)return i(!1),o.style.display="none",g.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(t){console.log(t)}finally{i(!1)}}f.addEventListener("submit",$);o.addEventListener("click",k);
//# sourceMappingURL=index.js.map
