import{a as S,S as q,i as y}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",M="46106680-1f6bf9cc8c5ebc2359fb269e0";let h=15;async function b(t,r){const a={q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:h,_page:r},s=new URLSearchParams(a);return(await S.get(`${w}?key=${M}&${s}`)).data}let $=document.querySelector(".gallery"),i=1;const P=document.querySelector(".div-loader"),x=document.querySelector(".div-loader-2");function l(t){y.error({title:"Error",message:t})}function f(t){P.style.visibility=t?"visible":"hidden"}function c(t){x.style.visibility=t?"visible":"hidden"}function v({webformatURL:t,largeImageURL:r,tags:a,likes:s,views:e,comments:o,downloads:n}){return`<li class="image">
        <a class = "gallery-link" href = "${r}">  
        <img src = "${t}" alt = "${a}" class = "image" />
        </a>
        <div class = "card-body">   
          <p class="text">Likes <span class = "value">${s}</span></p>
          <p class="text">Views <span class = "value">${e}</span></p>
          <p class="text">Comments <span class = "value">${o}</span></p>
          <p class="text">Downloads <span class = "value">${n}</span></p>
          </div>
        </li>`}const L=new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});async function k(){c(!0);const t=Math.ceil(100/h);if(i>t)return c(!1),y.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});try{const a=(await b(d,i)).hits.map(v).join("");$.insertAdjacentHTML("beforeend",a);const{height:s}=document.querySelector(".image img").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),p.style.display="flex",L.refresh(),i+=1}catch(r){console.log(r)}finally{c(!1)}}document.head.insertAdjacentHTML("beforeend",`<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@0;1&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap" rel="stylesheet">`);let m=document.querySelector(".gallery");const g=document.querySelector(".btn"),E=document.querySelector(".container");let p=document.querySelector(".load-btn"),u=1,d="";function O(t){t.preventDefault();const r=t.currentTarget,a=r.elements.query.value.trim();if(!a){l("Sorry, there are no images matching your search query. Please try again!");return}m.innerHTML="",f(!0),g.disabled=!0,d=a,u=1,b(d,u).then(s=>{if(s.hits.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}const e=s.hits.map(v).join("");m.insertAdjacentHTML("beforeend",e),p.style.display="flex",L.refresh(),r.reset(),u+=1}).catch(s=>{l(s.message)}).finally(()=>{f(!1),g.disabled=!1})}E.addEventListener("submit",O);p.addEventListener("click",k);
//# sourceMappingURL=index.js.map
